game: hyperbeatz
system: nes
poll_seconds: 0.10
telemetry:
  fields:
    p1_hp: { addr: 0x0035, type: u8 }
    p2_hp: { addr: 0x0036, type: u8 }
    p1_shadow: { addr: 0x0037, type: u8 }
    p2_shadow: { addr: 0x0038, type: u8 }
    p1_score: { addr: 0x0740, type: u16, endian: little }
    p2_score: { addr: 0x0742, type: u16, endian: little }
    p1_miss: { addr: 0x074E, type: u8 }
    p1_poor: { addr: 0x0750, type: u8 }
    p1_good: { addr: 0x0752, type: u8 }
    p1_nice: { addr: 0x0754, type: u8 }

triggers:
  - name: p1_hp_down
    when:
      field: p1_hp
      compare: decreased
    events:
      - name: HIT_STRONG
        target: p1

  - name: p1_hp_up
    when:
      field: p1_hp
      compare: increased
    events:
      - name: RELEASE
        target: p1

  - name: p1_nice_incremented
    when:
      field: p1_nice
      compare: increased
    events:
      - name: PULSE_DOUBLE_SHORT
        target: p1

  - name: p1_miss_incremented
    when:
      field: p1_miss
      compare: increased
    events:
      - name: PULSE_SINGLE_LONG
        target: p1
